### ISSUE TITLE
namespace

### ISSUE THREAD

**Issue by ehsandavari** [imaun/pardakhtyari#2]
سلام namespace فایل ShaparakBuilderExtension اشتباه زده شده و در زمان نصب با ناگت به درستی نصب نمیشه

**Comment by imaun** [comment]
سلام
لطفاً بفرمایید منظورتان از به درستی نصب نمیشه با نیوگت چیه؟ خطا می گیرید یا چیز دیگه ای مشکل.
در مورد namespace اون فایل هم، اشتباه نوشته نشده، در حقیقت best practice در این مورد استفاده از فضای نام Microsoft هست که وقتی می خواهید سرویس را به DI اضافه کنید نیازی به نوشتن using اضافی در فایل خودتون نداشته باشید.

البته در نهایت من قصد دارم توسعه این کتابخانه را در [اینجا](https://github.com/pardakhtyar/shaparak) ادامه بدم، اگر در حال حاضر درگیر در پروژه های پرداخت یاری هستین و داوطلب برای مشارکت هستید حتماً به من پیام بدین.
